ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'SENT';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'PAID';

ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "sent_at" TIMESTAMP(3);
ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "due_date" DATE;
ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "paid_at" TIMESTAMP(3);
